export const projectsData = [
  // Completed Projects
  {
    id: 1,
    name: "Highway Expansion Project",
    category: "Road Work",
    location: "Chennai - Bangalore Highway",
    status: "Completed",
    summary: "Major highway expansion including earthmoving and road construction for improved traffic flow.",
    description: "This comprehensive highway expansion project involved widening a critical 25-kilometer stretch of the Chennai-Bangalore highway. Our team successfully completed extensive earthmoving operations, including cut and fill work, embankment construction, and precise grading to meet highway engineering standards.",
    scope: "Highway widening, earthmoving, embankment construction, drainage systems, and road surface preparation",
    machinery: "Excavators (380, 215, 200), Motor Graders, Compactors, Dump Trucks, Bulldozers",
    duration: "18 months",
    challenges: "Working around existing traffic flow while maintaining safety standards and meeting tight deadlines during monsoon season."
  },
  {
    id: 2,
    name: "Industrial Site Development",
    category: "Earthmoving",
    location: "Coimbatore Industrial Area",
    status: "Completed",
    summary: "Complete site preparation and grading for large-scale industrial complex development.",
    description: "Comprehensive site development for a 50-acre industrial complex including complete site clearing, precision grading, and infrastructure preparation. The project required extensive earthmoving to create level platforms for multiple manufacturing units and supporting infrastructure.",
    scope: "Site clearing, mass excavation, grading, utility trenching, access road construction, and stormwater management",
    machinery: "Large Excavators (380, 300), Bulldozers, Compactors, Articulated Dump Trucks, Motor Graders",
    duration: "12 months",
    challenges: "Managing complex drainage requirements and coordinating with multiple utility installations while maintaining project timeline."
  },
  {
    id: 3,
    name: "Residential Complex Foundation",
    category: "Site Preparation",
    location: "Thottipalayam, Coimbatore",
    status: "Completed",
    summary: "Site clearing and foundation preparation for 200-unit residential development project.",
    description: "Large-scale residential development project requiring comprehensive site preparation for 200 housing units across 30 acres. Work included complete site clearing, topsoil management, foundation excavation, and utility infrastructure preparation.",
    scope: "Site clearing, topsoil stripping and stockpiling, foundation excavation, utility trenching, road base preparation",
    machinery: "Excavators (215, 200, 140), Compactors, Dump Trucks, Bulldozers, Mini Excavators for precision work",
    duration: "8 months",
    challenges: "Preserving existing mature trees as per environmental requirements while efficiently clearing development areas."
  },
  {
    id: 4,
    name: "Mining Operations Support",
    category: "Mining",
    location: "Salem District",
    status: "Completed",
    summary: "Heavy equipment support and material handling for granite quarry operations.",
    description: "Comprehensive mining support services for a major granite quarry operation including overburden removal, material handling, and quarry development. Our team provided specialized equipment and operators for efficient and safe mining operations.",
    scope: "Overburden removal, quarry bench development, material loading and hauling, access road maintenance",
    machinery: "Heavy Excavators (380, 300), Articulated Dump Trucks, Bulldozers, Wheel Loaders",
    duration: "24 months",
    challenges: "Operating in challenging terrain while maintaining strict safety protocols and environmental compliance."
  },
  {
    id: 5,
    name: "Bridge Construction Support",
    category: "Infrastructure",
    location: "Erode - Karur Route",
    status: "Completed",
    summary: "Earthmoving and site preparation for major bridge construction project.",
    description: "Critical infrastructure project providing earthmoving support for a major bridge construction spanning the Kaveri River. Work included approach road construction, abutment excavation, and material handling for bridge construction activities.",
    scope: "Approach road earthwork, abutment and pier foundation excavation, material handling, temporary access construction",
    machinery: "Excavators (300, 215), Long Reach Excavators, Compactors, Dump Trucks, Cranes",
    duration: "15 months",
    challenges: "Working in flood-prone areas with strict environmental controls and coordinating with bridge construction timeline."
  },
  {
    id: 6,
    name: "Airport Runway Extension",
    category: "Infrastructure",
    location: "Coimbatore Airport",
    status: "Completed",
    summary: "Precision earthmoving and grading for airport runway extension and taxiway development.",
    description: "High-precision earthmoving project for airport infrastructure expansion including runway extension and new taxiway construction. Work required extremely tight tolerances and coordination with ongoing airport operations.",
    scope: "Precision grading, runway extension earthwork, taxiway construction, drainage systems, utility relocation",
    machinery: "Motor Graders, Compactors, Excavators (200, 140), Articulated Dump Trucks, Specialized Airport Equipment",
    duration: "10 months",
    challenges: "Maintaining airport operations while working within strict aviation safety protocols and achieving millimeter-level precision."
  },

  // Ongoing Projects
  {
    id: 7,
    name: "Smart City Infrastructure",
    category: "Urban Development",
    location: "Coimbatore Smart City",
    status: "Ongoing",
    summary: "Comprehensive infrastructure development including roads, utilities, and site preparation.",
    description: "Major smart city infrastructure development project encompassing multiple phases of urban development. Current work includes road network development, utility corridor preparation, and site development for smart city facilities.",
    scope: "Road network construction, utility corridor development, site preparation for smart facilities, stormwater management",
    machinery: "Excavators (300, 215, 200), Motor Graders, Compactors, Dump Trucks, Utility Installation Equipment",
    duration: "36 months (ongoing - 18 months completed)",
    challenges: "Coordinating with multiple stakeholders while maintaining city services and integrating smart technology infrastructure."
  },
  {
    id: 8,
    name: "Industrial Park Development",
    category: "Earthmoving",
    location: "Tirupur Industrial Zone",
    status: "Ongoing",
    summary: "Large-scale earthmoving and site development for new industrial park complex.",
    description: "Massive industrial park development covering 200 acres with multiple phases of construction. Current phase involves major earthmoving operations, site grading, and infrastructure preparation for manufacturing facilities.",
    scope: "Mass earthmoving, site grading, internal road construction, utility infrastructure, stormwater management systems",
    machinery: "Large Excavators (380, 300), Bulldozers, Motor Graders, Articulated Dump Trucks, Compaction Equipment",
    duration: "48 months (ongoing - 24 months completed)",
    challenges: "Managing large-scale earth movement while coordinating with multiple industrial facility construction schedules."
  },
  {
    id: 9,
    name: "Coastal Protection Works",
    category: "Marine Engineering",
    location: "Rameswaram Coast",
    status: "Ongoing",
    summary: "Rock revetment and coastal erosion protection for critical shoreline infrastructure.",
    description: "Critical coastal protection project involving rock revetment construction and shoreline stabilization to protect vital infrastructure from coastal erosion. Work includes specialized marine construction techniques and environmental protection measures.",
    scope: "Rock revetment construction, shoreline stabilization, breakwater construction, beach nourishment, access road construction",
    machinery: "Long Reach Excavators, Marine Equipment, Rock Placement Equipment, Dump Trucks, Compactors",
    duration: "30 months (ongoing - 12 months completed)",
    challenges: "Working in marine environment with tidal constraints, weather dependencies, and strict environmental protection requirements."
  },
  {
    id: 10,
    name: "Township Road Network",
    category: "Road Work",
    location: "Pollachi Township",
    status: "Ongoing",
    summary: "Complete road network development for new residential township project.",
    description: "Comprehensive road network development for a new residential township covering 150 acres. Project includes main arterial roads, residential streets, pedestrian pathways, and complete utility infrastructure integration.",
    scope: "Road network construction, utility integration, stormwater drainage, street lighting preparation, landscaping earthwork",
    machinery: "Motor Graders, Excavators (200, 140), Compactors, Dump Trucks, Utility Installation Equipment",
    duration: "20 months (ongoing - 8 months completed)",
    challenges: "Coordinating road construction with residential building schedules and ensuring proper utility integration throughout the network."
  },
  {
    id: 11,
    name: "Quarry Expansion Project",
    category: "Mining",
    location: "Dharmapuri District",
    status: "Ongoing",
    summary: "Quarry expansion and modernization with advanced crushing and screening operations.",
    description: "Major quarry expansion project involving development of new extraction areas, modernization of processing facilities, and implementation of advanced crushing and screening operations for improved efficiency and environmental compliance.",
    scope: "Quarry expansion, overburden removal, processing plant site preparation, access road development, environmental compliance work",
    machinery: "Heavy Excavators (380, 300), Bulldozers, Articulated Dump Trucks, Wheel Loaders, Specialized Mining Equipment",
    duration: "42 months (ongoing - 18 months completed)",
    challenges: "Expanding operations while maintaining continuous production, implementing new environmental standards, and managing complex logistics."
  },
  {
    id: 12,
    name: "Metro Rail Foundation",
    category: "Infrastructure",
    location: "Coimbatore Metro Phase 2",
    status: "Ongoing",
    summary: "Foundation work and earthmoving support for metro rail expansion project.",
    description: "Critical infrastructure project providing comprehensive earthmoving and foundation support for Coimbatore Metro Rail Phase 2 expansion. Work includes station foundation preparation, tunnel approach construction, and utility relocation.",
    scope: "Station foundation excavation, tunnel approach construction, utility relocation, access road construction, material handling",
    machinery: "Excavators (300, 215), Specialized Foundation Equipment, Dump Trucks, Compactors, Cranes",
    duration: "60 months (ongoing - 30 months completed)",
    challenges: "Working in urban environment with minimal disruption to city traffic, coordinating with complex metro construction timeline, and managing deep excavation safety."
  }
];