export const projectsData = [
  // Completed Projects
  {
    id: 1,
    name: "Lake Development Project",
    category: "Earthmoving",
    location: "Valankulam Lake",
    status: "Completed",
    summary: "Complete lake bed excavation and embankment construction for water conservation project.",
    description: "Comprehensive lake development project for R.R.Thulasi Builders involving extensive excavation work, embankment construction, and site preparation. The project enhanced water storage capacity and improved local water management infrastructure.",
    scope: "Lake bed excavation, embankment construction, site preparation, drainage channel development",
    machinery: "EX-140, JCB, Tipper (1To6 Unit), Dozer",
    duration: "8 months",
    challenges: "Managing water table fluctuations and ensuring proper soil compaction for embankment stability."
  },
  {
    id: 2,
    name: "Commercial Complex Development",
    category: "Site Preparation",
    location: "Semmozhi Poonga, CBE",
    status: "Completed",
    summary: "Multi-phase site development for commercial complex with comprehensive earthmoving operations.",
    description: "Large-scale commercial development project for R.R.Thulasi Builders requiring extensive earthmoving, excavation, and site preparation. The project involved multiple phases of construction support with diverse machinery deployment for optimal efficiency.",
    scope: "Site clearing, mass excavation, grading, foundation preparation, utility trenching",
    machinery: "JCB, Mini Roller, Bobcat, Dozer, Tipper (1To6 Unit), Chain Dozer, EX-210, EX-140, EX-130, EX-110, EX-30+, EX-81",
    duration: "14 months",
    challenges: "Coordinating multiple construction phases while maintaining site access and managing complex utility relocations."
  },
  {
    id: 3,
    name: "Railway Infrastructure Support",
    category: "Infrastructure",
    location: "Palani Railway Work",
    status: "Completed",
    summary: "Specialized earthmoving and compaction work for railway infrastructure development.",
    description: "Critical railway infrastructure project for R.R.Thulasi Builders providing earthmoving support and soil compaction services. Work included track bed preparation, embankment construction, and precision grading to meet railway engineering standards.",
    scope: "Track bed preparation, embankment construction, soil compaction, drainage systems",
    machinery: "EX-130, Soil Compactor",
    duration: "6 months",
    challenges: "Working within railway safety protocols while maintaining precise elevation requirements for track installation."
  },
  {
    id: 4,
    name: "Industrial Site Compaction",
    category: "Site Preparation",
    location: "Palakad",
    status: "Completed",
    summary: "Soil compaction and site preparation for industrial facility construction.",
    description: "Industrial site preparation project for R.R.Thulasi Builders focusing on soil compaction and ground stabilization for manufacturing facility construction. Work ensured proper foundation support and site drainage for industrial operations.",
    scope: "Soil compaction, ground stabilization, site leveling, drainage preparation",
    machinery: "Soil Compactor",
    duration: "4 months",
    challenges: "Achieving required compaction density across varying soil conditions while meeting tight construction schedule."
  },
  {
    id: 5,
    name: "Residential Site Development",
    category: "Earthmoving",
    location: "Thenkasi",
    status: "Completed",
    summary: "Site excavation and preparation for residential development project.",
    description: "Residential development project for R.R.Thulasi Builders requiring precise excavation work and site preparation. The project involved careful earthmoving operations to create optimal building platforms while preserving natural drainage patterns.",
    scope: "Site excavation, building platform preparation, access road construction, utility preparation",
    machinery: "EX-130",
    duration: "5 months",
    challenges: "Preserving existing vegetation where possible while creating level building sites on sloped terrain."
  },
  {
    id: 6,
    name: "Infrastructure Material Supply",
    category: "Material Handling",
    location: "Vedasandur",
    status: "Completed",
    summary: "Material transportation and site support for infrastructure development project.",
    description: "Infrastructure support project for Selvamadhu Infra LLP involving efficient material transportation and site logistics management. The project ensured timely delivery of construction materials and site preparation support.",
    scope: "Material transportation, site logistics, construction support, access road maintenance",
    machinery: "Tipper (6 Unit)",
    duration: "10 months",
    challenges: "Coordinating material delivery schedules with construction timeline while managing site access in challenging terrain."
  },
  {
    id: 7,
    name: "Township Infrastructure Development",
    category: "Infrastructure",
    location: "Madukkarai",
    status: "Completed",
    summary: "Material handling and logistics support for township infrastructure development.",
    description: "Township development project for Sankaranand Infra involving comprehensive material handling and transportation services. The project supported multiple phases of infrastructure development with efficient logistics management.",
    scope: "Material transportation, infrastructure support, site logistics, construction material handling",
    machinery: "Tipper (6 Unit)",
    duration: "12 months",
    challenges: "Managing high-volume material transportation while coordinating with multiple construction activities across the township."
  },
  {
    id: 8,
    name: "Residential Complex Construction",
    category: "Site Preparation",
    location: "Karupparayanpala",
    status: "Completed",
    summary: "Comprehensive site development for residential complex with multi-equipment deployment.",
    description: "Large residential complex development for Zenvistas Realty Ventures LLP requiring extensive earthmoving, compaction, and material handling. The project involved coordinated deployment of multiple equipment types for efficient execution.",
    scope: "Site preparation, earthmoving, soil compaction, material handling, access road construction",
    machinery: "JCB, Mini Roller, Bobcat, Dozer, Soil Compactor, Tipper (1To6 Unit), EX-140, EX-81, EX-30+",
    duration: "16 months",
    challenges: "Coordinating multiple equipment operations while maintaining site safety and meeting residential construction standards."
  },
  {
    id: 9,
    name: "Commercial Development Support",
    category: "Earthmoving",
    location: "Peedampalli, CBE",
    status: "Completed",
    summary: "Earthmoving and material handling for commercial property development.",
    description: "Commercial property development project for Sri Baby Property Developers Private Limited requiring specialized earthmoving operations and material transportation. The project involved precise site preparation and efficient logistics management.",
    scope: "Site earthmoving, material transportation, site preparation, construction support",
    machinery: "Dozer, JCB, Tipper (3 Unit)",
    duration: "9 months",
    challenges: "Working in urban environment while minimizing disruption to surrounding commercial activities."
  },
  {
    id: 10,
    name: "Infrastructure Excavation Project",
    category: "Excavation",
    location: "Cheyyur, Chennai",
    status: "Completed",
    summary: "Specialized excavation work for infrastructure development project.",
    description: "Infrastructure development project for SPL Infrastructure Pvt Ltd requiring precision excavation work. The project involved careful earthmoving operations to support critical infrastructure installation and development.",
    scope: "Precision excavation, infrastructure support, site preparation, utility installation support",
    machinery: "EX-140",
    duration: "7 months",
    challenges: "Maintaining precision excavation standards while working around existing infrastructure and utilities."
  },
  {
    id: 11,
    name: "Heavy Excavation Operations",
    category: "Excavation",
    location: "Peralam",
    status: "Completed",
    summary: "Large-scale excavation project using heavy machinery for infrastructure development.",
    description: "Major excavation project for Shri Selliyamman Infra involving heavy-duty excavation operations. The project required specialized heavy machinery to handle challenging excavation requirements and site conditions.",
    scope: "Heavy excavation, mass earthmoving, site preparation, material handling",
    machinery: "EX-380",
    duration: "11 months",
    challenges: "Managing large-scale excavation operations while ensuring site stability and safety protocols."
  },
  {
    id: 12,
    name: "Industrial Excavation Project",
    category: "Excavation",
    location: "Ariyalur",
    status: "Completed",
    summary: "Industrial site excavation and preparation for manufacturing facility development.",
    description: "Industrial development project for RR Enterprises involving comprehensive excavation work and site preparation. The project supported manufacturing facility construction with precise earthmoving operations.",
    scope: "Industrial site excavation, foundation preparation, site grading, utility preparation",
    machinery: "EX-210",
    duration: "8 months",
    challenges: "Meeting industrial construction standards while managing complex soil conditions and drainage requirements."
  },
  {
    id: 13,
    name: "Site Compaction Project",
    category: "Site Preparation",
    location: "Pollachi",
    status: "Completed",
    summary: "Specialized compaction work for construction site preparation.",
    description: "Site preparation project for Roots Multiclean Ltd Unit-I involving specialized compaction operations. The project focused on achieving optimal soil density and stability for construction foundation requirements.",
    scope: "Site compaction, ground preparation, foundation support, soil stabilization",
    machinery: "Mini Roller",
    duration: "3 months",
    challenges: "Achieving uniform compaction across varying soil types while meeting strict foundation requirements."
  },
  {
    id: 14,
    name: "Construction Site Development",
    category: "Site Preparation",
    location: "Kaniyur",
    status: "Completed",
    summary: "Multi-equipment site development for construction project.",
    description: "Construction site development project for Karunanidhi Construction Private Limited requiring coordinated deployment of compaction equipment. The project involved comprehensive site preparation and ground stabilization work.",
    scope: "Site development, compaction work, ground stabilization, construction preparation",
    machinery: "Mini Roller, Hand Roller",
    duration: "5 months",
    challenges: "Coordinating multiple compaction operations while maintaining site access for ongoing construction activities."
  },
  {
    id: 15,
    name: "Infrastructure Site Preparation",
    category: "Excavation",
    location: "Thiruthani",
    status: "Completed",
    summary: "Site excavation and preparation for infrastructure development.",
    description: "Infrastructure development project for Repplen Projects Private Limited involving specialized excavation work. The project required precision earthmoving operations to support infrastructure installation and development.",
    scope: "Site excavation, infrastructure preparation, earthmoving, utility support",
    machinery: "EX-30+",
    duration: "6 months",
    challenges: "Working with compact excavator in confined spaces while maintaining precision excavation standards."
  },
  {
    id: 16,
    name: "Site Compaction Operations",
    category: "Site Preparation",
    location: "Thiruchendur",
    status: "Completed",
    summary: "Specialized compaction work for site development project.",
    description: "Site development project for PKY Enterprises involving specialized compaction operations. The project focused on ground preparation and soil stabilization for construction foundation requirements.",
    scope: "Site compaction, ground preparation, soil stabilization, foundation support",
    machinery: "Mini Roller",
    duration: "4 months",
    challenges: "Achieving required compaction standards in coastal soil conditions while managing environmental considerations."
  },
  {
    id: 17,
    name: "Multi-Phase Infrastructure Project",
    category: "Infrastructure",
    location: "Thiruvarur",
    status: "Completed",
    summary: "Large-scale infrastructure development with multiple excavator deployment.",
    description: "Comprehensive infrastructure development project for Searock Infrastructure involving multiple phases of excavation and earthmoving work. The project required coordinated deployment of various excavator types for optimal efficiency.",
    scope: "Infrastructure development, multi-phase excavation, earthmoving, site preparation",
    machinery: "EX-140, EX-210, EX-200",
    duration: "18 months",
    challenges: "Coordinating multiple excavator operations across different project phases while maintaining construction timeline."
  },
  {
    id: 18,
    name: "Coastal Infrastructure Development",
    category: "Infrastructure",
    location: "Kumbakonam",
    status: "Completed",
    summary: "Infrastructure development project with heavy excavation operations.",
    description: "Infrastructure development project for Searock Infrastructure involving heavy excavation and earthmoving operations. The project required specialized equipment deployment for challenging site conditions and infrastructure requirements.",
    scope: "Heavy excavation, infrastructure development, earthmoving, site preparation",
    machinery: "EX-140, EX-215",
    duration: "12 months",
    challenges: "Managing heavy excavation operations in challenging terrain while meeting infrastructure development standards."
  },
  {
    id: 19,
    name: "Regional Infrastructure Support",
    category: "Infrastructure",
    location: "Mayiladuthurai",
    status: "Completed",
    summary: "Regional infrastructure project with coordinated excavation operations.",
    description: "Regional infrastructure development project for Searock Infrastructure involving coordinated excavation and earthmoving operations. The project supported critical infrastructure development with efficient equipment deployment.",
    scope: "Regional infrastructure support, excavation operations, earthmoving, construction support",
    machinery: "EX-140, EX-210",
    duration: "10 months",
    challenges: "Coordinating regional infrastructure requirements while managing complex logistics and equipment deployment."
  },
  {
    id: 20,
    name: "Site Excavation Project",
    category: "Excavation",
    location: "Karaikkal",
    status: "Completed",
    summary: "Specialized excavation work for infrastructure development.",
    description: "Infrastructure development project for Searock Infrastructure requiring specialized excavation operations. The project involved precision earthmoving work to support critical infrastructure installation and site development.",
    scope: "Site excavation, infrastructure support, precision earthmoving, construction preparation",
    machinery: "EX-140",
    duration: "7 months",
    challenges: "Maintaining precision excavation standards while working in coastal environment with specific soil conditions."
  },
  {
    id: 21,
    name: "Heavy Equipment Operations",
    category: "Excavation",
    location: "Ranipet",
    status: "Completed",
    summary: "Heavy excavation project using specialized equipment.",
    description: "Heavy excavation project for Searock Infrastructure involving specialized heavy equipment operations. The project required advanced excavation capabilities to handle challenging site conditions and infrastructure requirements.",
    scope: "Heavy excavation, specialized operations, site preparation, infrastructure support",
    machinery: "EX-200",
    duration: "9 months",
    challenges: "Operating heavy equipment in challenging conditions while maintaining safety protocols and excavation precision."
  },
  {
    id: 22,
    name: "Specialized Excavation Operations",
    category: "Excavation",
    location: "Chennai-Kamaraj Port",
    status: "Completed",
    summary: "Specialized excavation with bucket and hard rock breaker operations.",
    description: "Specialized excavation project for Searock Infrastructure involving advanced excavation techniques including bucket operations and hard rock breaking. The project required specialized equipment for challenging excavation conditions.",
    scope: "Specialized excavation, hard rock breaking, bucket operations, site preparation",
    machinery: "EX-210 (Bucket and Hard Rock Breaker)",
    duration: "11 months",
    challenges: "Managing specialized excavation operations in port environment while coordinating with ongoing port activities."
  },
  {
    id: 23,
    name: "Infrastructure Excavation Support",
    category: "Infrastructure",
    location: "Anthiyur",
    status: "Completed",
    summary: "Infrastructure development with coordinated excavation operations.",
    description: "Infrastructure development project for Searock Infrastructure involving coordinated excavation and earthmoving operations. The project supported critical infrastructure development with efficient equipment deployment and site preparation.",
    scope: "Infrastructure excavation, coordinated operations, earthmoving, site development",
    machinery: "EX-140, EX-210",
    duration: "13 months",
    challenges: "Coordinating multiple excavation operations while maintaining infrastructure development timeline and quality standards."
  },
  {
    id: 24,
    name: "Construction Support Project",
    category: "Construction Support",
    location: "Kumbakonam",
    status: "Completed",
    summary: "Construction support services with excavation operations.",
    description: "Construction support project for Sripathy Associates Private Limited involving excavation and earthmoving operations. The project provided comprehensive construction support with efficient equipment deployment and site management.",
    scope: "Construction support, excavation operations, earthmoving, site management",
    machinery: "EX-140, EX-210",
    duration: "8 months",
    challenges: "Providing continuous construction support while coordinating with multiple construction activities and maintaining site efficiency."
  },
  {
    id: 25,
    name: "Site Development Project",
    category: "Site Preparation",
    location: "Nachiyarkovil",
    status: "Completed",
    summary: "Site development and excavation for construction project.",
    description: "Site development project for Sripathy Associates Private Limited involving excavation and site preparation work. The project focused on creating optimal construction conditions through efficient earthmoving and site development operations.",
    scope: "Site development, excavation work, site preparation, construction support",
    machinery: "EX-140",
    duration: "6 months",
    challenges: "Achieving optimal site conditions while managing local environmental considerations and construction requirements."
  },
  {
    id: 26,
    name: "Multi-Equipment Construction Support",
    category: "Construction Support",
    location: "Anakkarai",
    status: "Completed",
    summary: "Comprehensive construction support with multiple excavator deployment.",
    description: "Comprehensive construction support project for Sripathy Associates Private Limited involving coordinated deployment of multiple excavators. The project provided efficient construction support through strategic equipment utilization and site management.",
    scope: "Multi-equipment support, construction operations, excavation work, site coordination",
    machinery: "EX-140, EX-210",
    duration: "14 months",
    challenges: "Coordinating multiple excavator operations while maintaining construction support efficiency and meeting project deadlines."
  },
  {
    id: 27,
    name: "Infrastructure Construction Support",
    category: "Infrastructure",
    location: "Thiruvarur",
    status: "Completed",
    summary: "Infrastructure construction support with heavy excavation operations.",
    description: "Infrastructure construction support project for Sripathy Associates Private Limited involving heavy excavation and earthmoving operations. The project supported critical infrastructure development with specialized equipment deployment.",
    scope: "Infrastructure support, heavy excavation, earthmoving operations, construction coordination",
    machinery: "EX-140, EX-200",
    duration: "12 months",
    challenges: "Supporting infrastructure construction while managing heavy excavation operations and maintaining construction timeline."
  },
  {
    id: 28,
    name: "Regional Construction Project",
    category: "Construction Support",
    location: "Mayiladuthurai",
    status: "Completed",
    summary: "Regional construction support with specialized excavation operations.",
    description: "Regional construction support project for Sripathy Associates Private Limited involving specialized excavation and earthmoving operations. The project provided comprehensive construction support across regional development requirements.",
    scope: "Regional construction support, specialized excavation, earthmoving, project coordination",
    machinery: "EX-140, EX-215",
    duration: "15 months",
    challenges: "Managing regional construction support while coordinating specialized excavation operations across multiple project areas."
  },
  {
    id: 29,
    name: "Heavy Excavation Project",
    category: "Excavation",
    location: "Thanjavur",
    status: "Completed",
    summary: "Heavy excavation operations for infrastructure development.",
    description: "Heavy excavation project for Sripathy Associates Private Limited involving specialized heavy excavation operations. The project required advanced excavation capabilities to support infrastructure development and site preparation requirements.",
    scope: "Heavy excavation, infrastructure development, site preparation, specialized operations",
    machinery: "EX-215",
    duration: "10 months",
    challenges: "Managing heavy excavation operations while ensuring site stability and meeting infrastructure development standards."
  },
  {
    id: 30,
    name: "Infrastructure Development Support",
    category: "Infrastructure",
    location: "Hosur",
    status: "Completed",
    summary: "Infrastructure development with coordinated excavation operations.",
    description: "Infrastructure development project for AVP Infrastructure involving coordinated excavation and earthmoving operations. The project supported critical infrastructure development with efficient equipment deployment and construction support.",
    scope: "Infrastructure development, coordinated excavation, earthmoving, construction support",
    machinery: "EX-210, EX-215",
    duration: "16 months",
    challenges: "Coordinating infrastructure development while managing multiple excavation operations and maintaining construction quality."
  },
  {
    id: 31,
    name: "Regional Infrastructure Project",
    category: "Infrastructure",
    location: "Kundadam-Dharapuram",
    status: "Completed",
    summary: "Regional infrastructure development with excavation support.",
    description: "Regional infrastructure development project for AVP Infrastructure involving excavation and earthmoving operations. The project supported regional infrastructure improvements with efficient equipment deployment and site management.",
    scope: "Regional infrastructure development, excavation support, earthmoving, site management",
    machinery: "EX-210",
    duration: "11 months",
    challenges: "Managing regional infrastructure requirements while coordinating excavation operations across diverse site conditions."
  },
  {
    id: 32,
    name: "Compact Excavation Project",
    category: "Excavation",
    location: "Kumbakonam",
    status: "Completed",
    summary: "Compact excavation operations for specialized site work.",
    description: "Specialized excavation project for SRM Construction involving compact excavation operations. The project required precision earthmoving work in confined spaces with focus on efficiency and site optimization.",
    scope: "Compact excavation, precision earthmoving, site optimization, specialized operations",
    machinery: "EX-40",
    duration: "4 months",
    challenges: "Operating compact excavator in confined spaces while maintaining excavation precision and site access requirements."
  },
  {
    id: 33,
    name: "Material Handling Project",
    category: "Material Handling",
    location: "Irugur, Vellalore, Chettipalayam",
    status: "Completed",
    summary: "Multi-location material handling and transportation services.",
    description: "Multi-location material handling project for Selvamadhu Developers involving transportation and logistics operations across multiple sites. The project provided efficient material handling and construction support services.",
    scope: "Multi-location material handling, transportation services, logistics support, construction coordination",
    machinery: "JCB, Tipper (1 Unit)",
    duration: "13 months",
    challenges: "Managing material handling operations across multiple locations while coordinating transportation schedules and site requirements."
  },
  {
    id: 34,
    name: "Heavy Equipment Support",
    category: "Construction Support",
    location: "Kudavasal",
    status: "Completed",
    summary: "Heavy equipment support with trailer and excavation operations.",
    description: "Heavy equipment support project for AV Associates involving trailer operations and excavation work. The project provided comprehensive construction support with specialized equipment deployment and material handling capabilities.",
    scope: "Heavy equipment support, trailer operations, excavation work, material handling",
    machinery: "Trailer (12 Wheel), EX-140, EX-30+",
    duration: "12 months",
    challenges: "Coordinating heavy equipment operations while managing trailer logistics and maintaining construction support efficiency."
  },
  {
    id: 35,
    name: "Industrial Site Compaction",
    category: "Site Preparation",
    location: "Karaikkal",
    status: "Completed",
    summary: "Industrial site preparation with excavation and compaction operations.",
    description: "Industrial site preparation project for Welspun Enterprises Limited involving excavation and soil compaction operations. The project focused on creating optimal industrial site conditions through comprehensive earthmoving and compaction work.",
    scope: "Industrial site preparation, excavation operations, soil compaction, site optimization",
    machinery: "EX-210, Soil Compactor",
    duration: "9 months",
    challenges: "Meeting industrial site standards while managing excavation and compaction operations in challenging soil conditions."
  },
  {
    id: 36,
    name: "Specialized Equipment Operations",
    category: "Construction Support",
    location: "Navaindia, CBE",
    status: "Completed",
    summary: "Specialized construction support with compact equipment operations.",
    description: "Specialized construction support project for VRN Construction involving compact equipment operations. The project provided efficient construction support through strategic deployment of specialized compact machinery.",
    scope: "Specialized construction support, compact equipment operations, site work, construction coordination",
    machinery: "Bobcat",
    duration: "5 months",
    challenges: "Providing specialized construction support while managing compact equipment operations in confined construction environments."
  },
  {
    id: 37,
    name: "Construction Equipment Support",
    category: "Construction Support",
    location: "Navaindia, CBE",
    status: "Completed",
    summary: "Construction equipment support with compact machinery operations.",
    description: "Construction equipment support project for Nika CG Construction involving compact machinery operations. The project provided comprehensive construction support through efficient deployment of specialized compact equipment.",
    scope: "Construction equipment support, compact machinery operations, site support, construction coordination",
    machinery: "Bobcat",
    duration: "6 months",
    challenges: "Managing construction equipment support while coordinating compact machinery operations and maintaining construction efficiency."
  },
  {
    id: 38,
    name: "Site Compaction Operations",
    category: "Site Preparation",
    location: "Kannivadi, Tirupur",
    status: "Completed",
    summary: "Site preparation with specialized compaction operations.",
    description: "Site preparation project for Vebsarl India Projects Private Limited involving specialized soil compaction operations. The project focused on achieving optimal site conditions through comprehensive compaction and ground stabilization work.",
    scope: "Site preparation, specialized compaction, ground stabilization, site optimization",
    machinery: "Soil Compactor",
    duration: "7 months",
    challenges: "Achieving required compaction standards while managing diverse soil conditions and meeting site preparation requirements."
  },
  {
    id: 39,
    name: "Multi-Equipment Site Development",
    category: "Site Preparation",
    location: "Sungam, CBE",
    status: "Completed",
    summary: "Comprehensive site development with multiple equipment deployment.",
    description: "Comprehensive site development project for Udhayaskavi Construction Private Limited involving multiple equipment deployment including compaction and rolling operations. The project provided complete site preparation and development services.",
    scope: "Multi-equipment site development, compaction operations, rolling work, site preparation",
    machinery: "Soil Compactor, Mini Roller, Hand Roller",
    duration: "11 months",
    challenges: "Coordinating multiple equipment operations while maintaining site development efficiency and meeting comprehensive preparation requirements."
  },
  {
    id: 40,
    name: "Site Rolling Operations",
    category: "Site Preparation",
    location: "Thennampalayam",
    status: "Completed",
    summary: "Site preparation with specialized rolling operations.",
    description: "Site preparation project for Udhayaskavi Construction Private Limited involving specialized rolling operations. The project focused on site compaction and surface preparation through efficient rolling and compaction techniques.",
    scope: "Site preparation, specialized rolling, surface preparation, compaction work",
    machinery: "Mini Roller",
    duration: "4 months",
    challenges: "Achieving uniform surface preparation while managing rolling operations and meeting site preparation standards."
  },
  {
    id: 41,
    name: "Engineering Site Preparation",
    category: "Site Preparation",
    location: "Dindigul",
    status: "Completed",
    summary: "Engineering site preparation with compaction and rolling operations.",
    description: "Engineering site preparation project for Taamaesek Engineering Consortium involving compaction and rolling operations. The project provided comprehensive site preparation services with focus on engineering requirements and site optimization.",
    scope: "Engineering site preparation, compaction operations, rolling work, site optimization",
    machinery: "Mini Roller, Soil Compactor",
    duration: "8 months",
    challenges: "Meeting engineering site requirements while coordinating compaction and rolling operations across diverse site conditions."
  },
  {
    id: 42,
    name: "Construction Material Support",
    category: "Material Handling",
    location: "Gandhipuram, CBE",
    status: "Completed",
    summary: "Construction material handling and transportation services.",
    description: "Construction material handling project for M/S Pride Construction involving material transportation and construction support services. The project provided efficient logistics and material handling support for construction operations.",
    scope: "Construction material handling, transportation services, logistics support, construction coordination",
    machinery: "JCB, Tipper (3 Unit)",
    duration: "10 months",
    challenges: "Managing construction material logistics while coordinating transportation schedules and maintaining construction support efficiency."
  },
  {
    id: 43,
    name: "Site Compaction Project",
    category: "Site Preparation",
    location: "Chinnavedampatti",
    status: "Completed",
    summary: "Site preparation with specialized hand roller operations.",
    description: "Site preparation project for M/S Asvin Construction involving specialized hand roller operations. The project focused on precision compaction work in areas requiring detailed site preparation and surface finishing.",
    scope: "Site preparation, specialized compaction, precision rolling, surface finishing",
    machinery: "Hand Roller",
    duration: "3 months",
    challenges: "Achieving precision compaction in detailed areas while maintaining site preparation quality and meeting finishing requirements."
  },
  {
    id: 44,
    name: "Precision Site Preparation",
    category: "Site Preparation",
    location: "Singanallur",
    status: "Completed",
    summary: "Precision site preparation with hand roller operations.",
    description: "Precision site preparation project for M/S Asvin Construction involving detailed hand roller operations. The project provided specialized compaction services with focus on precision work and detailed site finishing requirements.",
    scope: "Precision site preparation, detailed compaction, specialized rolling, site finishing",
    machinery: "Hand Roller",
    duration: "4 months",
    challenges: "Managing precision site preparation while maintaining detailed compaction standards and achieving required site finishing quality."
  },
  {
    id: 45,
    name: "Heavy Construction Support",
    category: "Construction Support",
    location: "Idaiyakottai",
    status: "Completed",
    summary: "Comprehensive heavy construction support with multiple equipment deployment.",
    description: "Comprehensive heavy construction support project for Balaji & Co involving multiple equipment deployment including compaction, transportation, and specialized excavation operations. The project provided complete construction support services.",
    scope: "Heavy construction support, multi-equipment operations, compaction work, transportation services, specialized excavation",
    machinery: "Soil Compactor, Trailer (12 Wheel), EX-110, EX-130, EX-140, EX-210 (Bucket and Hard Rock Breaker), EX-215, Crane",
    duration: "20 months",
    challenges: "Coordinating comprehensive construction support while managing multiple equipment operations and maintaining construction efficiency across large project scope."
  },
  {
    id: 46,
    name: "Multi-Phase Construction Project",
    category: "Construction Support",
    location: "Vellakovil",
    status: "Completed",
    summary: "Multi-phase construction support with comprehensive equipment deployment.",
    description: "Multi-phase construction support project for Balaji & Co involving comprehensive equipment deployment including compaction, transportation, and excavation operations. The project provided complete construction support across multiple project phases.",
    scope: "Multi-phase construction support, comprehensive equipment deployment, compaction operations, transportation services, excavation work",
    machinery: "Soil Compactor, Trailer (12 Wheel), EX-110, EX-130, EX-140, EX-210, EX-215, Crane",
    duration: "22 months",
    challenges: "Managing multi-phase construction support while coordinating comprehensive equipment operations and maintaining project continuity across different phases."
  },
  {
    id: 47,
    name: "Infrastructure Excavation Operations",
    category: "Excavation",
    location: "Thottiyam",
    status: "Completed",
    summary: "Infrastructure excavation operations for construction support.",
    description: "Infrastructure excavation project for Ashok Construction involving specialized excavation operations. The project provided comprehensive excavation support for infrastructure development with focus on efficiency and construction coordination.",
    scope: "Infrastructure excavation, specialized operations, construction support, earthmoving",
    machinery: "EX-210",
    duration: "9 months",
    challenges: "Managing infrastructure excavation operations while coordinating with construction activities and maintaining excavation efficiency."
  },
  {
    id: 48,
    name: "Construction Excavation Support",
    category: "Excavation",
    location: "Namakkal",
    status: "Completed",
    summary: "Construction excavation support with specialized equipment operations.",
    description: "Construction excavation support project for Ashok Construction involving specialized excavation equipment operations. The project provided comprehensive excavation support with focus on construction coordination and site development.",
    scope: "Construction excavation support, specialized equipment operations, site development, construction coordination",
    machinery: "EX-210",
    duration: "8 months",
    challenges: "Providing construction excavation support while managing specialized equipment operations and maintaining construction timeline."
  },
  {
    id: 49,
    name: "New Construction Site Development",
    category: "Site Preparation",
    location: "Rasipuram New Construction",
    status: "Completed",
    summary: "New construction site development with excavation operations.",
    description: "New construction site development project for Anjani Construction involving excavation and site preparation operations. The project provided comprehensive site development services for new construction requirements.",
    scope: "New construction site development, excavation operations, site preparation, construction support",
    machinery: "EX-140",
    duration: "7 months",
    challenges: "Managing new construction site development while coordinating excavation operations and meeting construction preparation requirements."
  },
  {
    id: 50,
    name: "Heavy Excavation Operations",
    category: "Excavation",
    location: "Sulur, CBE",
    status: "Completed",
    summary: "Heavy excavation operations for construction development.",
    description: "Heavy excavation project for Arthida Creation involving specialized heavy excavation operations. The project required advanced excavation capabilities to support construction development and site preparation requirements.",
    scope: "Heavy excavation operations, construction development, site preparation, specialized excavation",
    machinery: "EX-215",
    duration: "10 months",
    challenges: "Managing heavy excavation operations while ensuring construction development standards and maintaining excavation precision."
  },
  {
    id: 51,
    name: "Construction Equipment Support",
    category: "Construction Support",
    location: "Avinashi to Gandhipuram",
    status: "Completed",
    summary: "Construction equipment support with multi-equipment operations.",
    description: "Construction equipment support project for KNR Construction involving multi-equipment operations across transportation route. The project provided comprehensive construction support with efficient equipment deployment and coordination.",
    scope: "Construction equipment support, multi-equipment operations, transportation route support, construction coordination",
    machinery: "JCB, Bobcat",
    duration: "11 months",
    challenges: "Managing construction equipment support across transportation route while coordinating multi-equipment operations and maintaining construction efficiency."
  },
  {
    id: 52,
    name: "Multi-Equipment Construction Support",
    category: "Construction Support",
    location: "Avinashi to Gandhipuram",
    status: "Completed",
    summary: "Comprehensive construction support with multiple equipment deployment.",
    description: "Comprehensive construction support project for Srri Khamakshi Constructions and Builders involving multiple equipment deployment including material handling and compaction operations. The project provided complete construction support services.",
    scope: "Multi-equipment construction support, material handling, compaction operations, construction coordination",
    machinery: "JCB, Tipper (6 Unit), Mini Roller",
    duration: "14 months",
    challenges: "Coordinating comprehensive construction support while managing multiple equipment operations and maintaining construction support efficiency."
  },
  {
    id: 53,
    name: "Specialized Construction Support",
    category: "Construction Support",
    location: "Sulur, CBE",
    status: "Completed",
    summary: "Specialized construction support with compaction operations.",
    description: "Specialized construction support project for Bull Machine Pvt Ltd involving compaction and specialized equipment operations. The project provided comprehensive construction support with focus on specialized operations and site optimization.",
    scope: "Specialized construction support, compaction operations, specialized equipment deployment, site optimization",
    machinery: "Dozer, Soil Compactor, Bobcat",
    duration: "12 months",
    challenges: "Managing specialized construction support while coordinating compaction operations and maintaining specialized equipment efficiency."
  },
  {
    id: 54,
    name: "Regional Site Compaction",
    category: "Site Preparation",
    location: "Hubli, Karnataka",
    status: "Completed",
    summary: "Regional site preparation with specialized compaction operations.",
    description: "Regional site preparation project for Klasscorp Solutions Pvt Ltd involving specialized soil compaction operations. The project provided comprehensive site preparation services across regional requirements with focus on compaction quality.",
    scope: "Regional site preparation, specialized compaction, soil stabilization, site optimization",
    machinery: "Soil Compactor",
    duration: "8 months",
    challenges: "Managing regional site preparation while coordinating specialized compaction operations across diverse regional conditions."
  },
  {
    id: 55,
    name: "Infrastructure Site Preparation",
    category: "Site Preparation",
    location: "Pappampatti Pirivu, CBE",
    status: "Completed",
    summary: "Infrastructure site preparation with compaction operations.",
    description: "Infrastructure site preparation project for Vinayagaa Infrastructure involving specialized compaction operations. The project provided comprehensive site preparation services with focus on infrastructure development requirements.",
    scope: "Infrastructure site preparation, specialized compaction, site development, infrastructure support",
    machinery: "Mini Roller",
    duration: "6 months",
    challenges: "Managing infrastructure site preparation while coordinating compaction operations and meeting infrastructure development standards."
  },
  {
    id: 56,
    name: "Multi-Equipment Site Development",
    category: "Site Preparation",
    location: "Kannampalayam, CBE",
    status: "Completed",
    summary: "Comprehensive site development with multiple equipment deployment.",
    description: "Comprehensive site development project for Bavida Builders involving multiple equipment deployment including compaction and specialized operations. The project provided complete site development services with focus on construction preparation.",
    scope: "Multi-equipment site development, compaction operations, specialized equipment deployment, construction preparation",
    machinery: "Soil Compactor, Mini Roller, Hand Roller, Bobcat",
    duration: "13 months",
    challenges: "Coordinating comprehensive site development while managing multiple equipment operations and maintaining site development efficiency."
  },
  {
    id: 57,
    name: "Regional Construction Support",
    category: "Construction Support",
    location: "Sungam and Singanallur",
    status: "Completed",
    summary: "Regional construction support with multi-equipment operations.",
    description: "Regional construction support project for Indra & Indra Private Limited involving multi-equipment operations across multiple locations. The project provided comprehensive construction support with efficient equipment deployment and coordination.",
    scope: "Regional construction support, multi-equipment operations, multi-location coordination, construction services",
    machinery: "JCB, Dozer, Tipper (3 to 6), Bobcat",
    duration: "16 months",
    challenges: "Managing regional construction support while coordinating multi-equipment operations across multiple locations and maintaining construction efficiency."
  },
  {
    id: 58,
    name: "Site Compaction Operations",
    category: "Site Preparation",
    location: "Sungam, CBE",
    status: "Completed",
    summary: "Site preparation with specialized hand roller operations.",
    description: "Site preparation project for Jain Coimbatore Projects involving specialized hand roller operations. The project provided precision compaction services with focus on detailed site preparation and surface finishing requirements.",
    scope: "Site preparation, specialized compaction, precision rolling, surface finishing",
    machinery: "Hand Roller",
    duration: "5 months",
    challenges: "Managing precision site preparation while maintaining specialized compaction standards and achieving required surface finishing quality."
  },

  // Ongoing Projects
  {
    id: 59,
    name: "Infrastructure Development Project",
    category: "Infrastructure",
    location: "Kallakurichi",
    status: "Ongoing",
    summary: "Large-scale infrastructure development with heavy excavation and site preparation work.",
    description: "Major infrastructure development project for AVP Infrastructure involving comprehensive excavation and earthmoving operations. The project requires coordinated deployment of heavy machinery for efficient site development and infrastructure preparation.",
    scope: "Heavy excavation, site preparation, infrastructure development, material handling, access road construction",
    machinery: "EX-210, EX-215",
    duration: "24 months (ongoing - 8 months completed)",
    challenges: "Coordinating heavy machinery operations while maintaining project timeline and managing complex site logistics."
  },
  {
    id: 60,
    name: "Multi-Phase Construction Support",
    category: "Construction Support",
    location: "Perumanallur",
    status: "Ongoing",
    summary: "Comprehensive construction support with excavation and crane operations for infrastructure project.",
    description: "Multi-phase infrastructure project for Likhitha Infrastructure requiring diverse equipment deployment including excavation, crane operations, and material handling. The project involves coordinated construction support across multiple work areas.",
    scope: "Excavation work, crane operations, material handling, construction support, site logistics",
    machinery: "EX-210, EX-215, Crane",
    duration: "30 months (ongoing - 12 months completed)",
    challenges: "Managing multiple equipment types while coordinating with various construction phases and maintaining site safety."
  },
  {
    id: 61,
    name: "Regional Development Project",
    category: "Earthmoving",
    location: "Kasargode, Kerala",
    status: "Ongoing",
    summary: "Regional infrastructure development with specialized excavation work.",
    description: "Regional development project for Sri Ganesh Construction involving specialized excavation operations and site preparation. The project supports infrastructure development across the Kerala border region with focus on efficient earthmoving operations.",
    scope: "Site excavation, earthmoving, infrastructure preparation, regional development support",
    machinery: "EX-140",
    duration: "18 months (ongoing - 6 months completed)",
    challenges: "Working across state boundaries while coordinating with local regulations and managing cross-regional logistics."
  },
  {
    id: 62,
    name: "District Infrastructure Support",
    category: "Infrastructure",
    location: "Sonur, Palakad",
    status: "Ongoing",
    summary: "District-level infrastructure development with excavation and site preparation services.",
    description: "District infrastructure development project for Sri Ganesh Construction focusing on excavation work and site preparation. The project supports regional infrastructure improvements with efficient earthmoving operations and construction support.",
    scope: "District infrastructure development, excavation work, site preparation, construction support",
    machinery: "EX-140",
    duration: "20 months (ongoing - 7 months completed)",
    challenges: "Coordinating district-level infrastructure requirements while managing diverse site conditions and local coordination."
  },
  {
    id: 63,
    name: "Commercial Excavation Project",
    category: "Excavation",
    location: "Aravakurichi",
    status: "Ongoing",
    summary: "Commercial development excavation work with precision earthmoving operations.",
    description: "Commercial development project for SAV Construction requiring precision excavation work and site preparation. The project involves careful earthmoving operations to support commercial facility construction with focus on site optimization.",
    scope: "Commercial site excavation, precision earthmoving, site optimization, construction preparation",
    machinery: "EX-210",
    duration: "15 months (ongoing - 5 months completed)",
    challenges: "Maintaining precision excavation standards while working within commercial development timeline and site constraints."
  },
  {
    id: 64,
    name: "Engineering Infrastructure Project",
    category: "Infrastructure",
    location: "Pollachi",
    status: "Ongoing",
    summary: "Engineering infrastructure development with specialized excavation and construction support.",
    description: "Engineering infrastructure project for Hitech Builders and Engineers involving specialized excavation work and comprehensive construction support. The project requires coordinated earthmoving operations and infrastructure development expertise.",
    scope: "Engineering infrastructure development, specialized excavation, construction support, site development",
    machinery: "EX-210",
    duration: "22 months (ongoing - 9 months completed)",
    challenges: "Meeting engineering specifications while coordinating complex infrastructure requirements and maintaining construction quality standards."
  },
  {
    id: 65,
    name: "Soil Compaction Project",
    category: "Site Preparation",
    location: "Gadag, Karnataka",
    status: "Ongoing",
    summary: "Specialized soil compaction and ground stabilization for infrastructure development.",
    description: "Infrastructure development project for KS Power (I) Pvt Ltd focusing on soil compaction and ground stabilization work. The project involves specialized compaction techniques to ensure proper foundation support for infrastructure construction.",
    scope: "Soil compaction, ground stabilization, foundation preparation, site optimization",
    machinery: "Soil Compactor",
    duration: "12 months (ongoing - 4 months completed)",
    challenges: "Achieving required compaction standards across varying soil conditions while coordinating with infrastructure construction schedule."
  },
  {
    id: 66,
    name: "Multi-Equipment Construction Support",
    category: "Construction Support",
    location: "Velliyanai, Karur",
    status: "Ongoing",
    summary: "Comprehensive construction support with soil compaction, material handling, and transportation services.",
    description: "Large-scale construction project for Balaji & Co requiring comprehensive equipment support including soil compaction, material transportation, and specialized trailer operations. The project involves coordinated deployment of multiple equipment types for efficient construction support.",
    scope: "Soil compaction, material transportation, construction support, specialized trailer operations, site logistics",
    machinery: "Soil Compactor, Tipper (6 Unit), Trailer (12 Wheel)",
    duration: "28 months (ongoing - 14 months completed)",
    challenges: "Coordinating multiple equipment operations while managing complex logistics and maintaining construction support efficiency across large project area."
  },
  {
    id: 67,
    name: "Development Site Preparation",
    category: "Site Preparation",
    location: "Irugur, Vellalore",
    status: "Ongoing",
    summary: "Site preparation and development support with construction equipment operations.",
    description: "Site preparation and development project for Selvamadhu Developers involving construction equipment operations and site development work. The project provides comprehensive site preparation services with focus on development requirements.",
    scope: "Site preparation, development support, construction equipment operations, site development",
    machinery: "JCB",
    duration: "16 months (ongoing - 6 months completed)",
    challenges: "Managing site preparation operations while coordinating development requirements and maintaining construction equipment efficiency."
  },
  {
    id: 68,
    name: "Specialized Construction Support",
    category: "Construction Support",
    location: "Sulur, CBE",
    status: "Ongoing",
    summary: "Specialized construction support with compaction operations.",
    description: "Specialized construction support project for Bull Machine Pvt Ltd involving compaction and specialized equipment operations. The project provides comprehensive construction support with focus on specialized operations and site optimization.",
    scope: "Specialized construction support, compaction operations, specialized equipment deployment, site optimization",
    machinery: "Soil Compactor",
    duration: "18 months (ongoing - 8 months completed)",
    challenges: "Managing specialized construction support while coordinating compaction operations and maintaining specialized equipment efficiency."
  },
  {
    id: 69,
    name: "Multi-Equipment Infrastructure Support",
    category: "Infrastructure",
    location: "Thirukoornam, Aravakurichi",
    status: "Ongoing",
    summary: "Comprehensive infrastructure support with multiple equipment deployment.",
    description: "Comprehensive infrastructure support project for Madhu Electricals and Engineering involving multiple equipment deployment including material handling, compaction, and excavation operations. The project provides complete infrastructure support services.",
    scope: "Multi-equipment infrastructure support, material handling, compaction operations, excavation work, construction coordination",
    machinery: "JCB, Mini Roller, Tipper (3To6 Unit), EX-140, EX-210, EX-215",
    duration: "32 months (ongoing - 16 months completed)",
    challenges: "Coordinating comprehensive infrastructure support while managing multiple equipment operations and maintaining construction support efficiency across large infrastructure project."
  }
];